# Generated by Django 2.0.2 on 2018-03-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of location', max_length=100)),
                ('description', models.TextField(help_text='Brief description of location', max_length=1000)),
                ('ratings', models.FloatField()),
                ('popularity', models.IntegerField()),
                ('comments', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='location_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter username', max_length=50)),
                ('password', models.CharField(help_text='Enter password', max_length=50)),
                ('location', models.CharField(help_text='location', max_length=100)),
                ('favorites', models.ManyToManyField(to='UncommonGrounds.Location')),
                ('user_tags', models.ManyToManyField(to='UncommonGrounds.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='tags',
            field=models.ManyToManyField(to='UncommonGrounds.Tag'),
        ),
    ]
