# Generated by Django 2.0.2 on 2018-03-27 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UncommonGrounds', '0004_auto_20180327_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UncommonGrounds.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loc_comments', to='UncommonGrounds.Comment'),
        ),
    ]
