# Generated by Django 2.0.2 on 2018-03-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UncommonGrounds', '0005_auto_20180327_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='ratings',
            field=models.IntegerField(blank=True, choices=[(0, ' '), (1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=' '),
        ),
    ]
