# Generated by Django 2.0.2 on 2018-04-07 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UncommonGrounds', '0008_auto_20180407_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='location_images/')),
                ('user_since', models.DateTimeField(auto_now_add=True)),
                ('favorites', models.ManyToManyField(related_name='faves', to='UncommonGrounds.Location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_tags', models.ManyToManyField(to='UncommonGrounds.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UncommonGrounds.Profile'),
        ),
        migrations.AddField(
            model_name='location',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UncommonGrounds.Profile'),
        ),
    ]
