# Generated by Django 2.0.2 on 2018-04-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UncommonGrounds', '0014_auto_20180408_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='ratings',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=' '),
        ),
    ]
