# Generated by Django 2.0.2 on 2018-04-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UncommonGrounds', '0015_auto_20180417_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_edit', 'can_view'),)},
        ),
    ]
