# Generated by Django 2.0.2 on 2018-04-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UncommonGrounds', '0016_auto_20180422_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
