# Generated by Django 2.0.2 on 2018-04-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UncommonGrounds', '0018_auto_20180422_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='bagface.jpg', upload_to='profile_images'),
        ),
    ]
