# Generated by Django 2.0.2 on 2018-04-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UncommonGrounds', '0021_auto_20180423_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile_images/bagface.jpg', upload_to='profile_images'),
        ),
    ]
