# Generated by Django 2.0.2 on 2018-03-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of location', max_length=100)),
                ('description', models.CharField(help_text='Brief description of location', max_length=1000)),
                ('ratings', models.FloatField()),
                ('popularity', models.IntegerField()),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter username', max_length=50)),
                ('password', models.CharField(help_text='Enter password', max_length=50)),
                ('location', models.CharField(help_text='location', max_length=100)),
            ],
        ),
    ]
