# Generated by Django 2.0.2 on 2018-03-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='location_images/'),
        ),
    ]
