# Generated by Django 2.0.2 on 2018-03-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_location_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='catalog.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(help_text='Brief description of location', max_length=1000),
        ),
        migrations.AddField(
            model_name='location',
            name='tags',
            field=models.ManyToManyField(to='catalog.Tags'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_tags',
            field=models.ManyToManyField(to='catalog.Tags'),
        ),
    ]
