# Generated by Django 2.0.2 on 2018-03-20 17:37

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('catalog', '0004_auto_20180320_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
