# Generated by Django 2.0.2 on 2018-03-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180320_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='tags',
            field=models.ManyToManyField(to='catalog.Tag'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_tags',
            field=models.ManyToManyField(to='catalog.Tag'),
        ),
    ]
