# Generated by Django 2.0.2 on 2018-03-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180320_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='comments',
            field=models.TextField(max_length=1000),
        ),
    ]
