# Generated by Django 2.0.2 on 2018-03-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180320_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(upload_to='location_images/'),
        ),
    ]
